config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	skip_before_action :verify_authenticity_token	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[ show edit update destroy ]

  # GET /pokemons or /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1 or /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons or /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to pokemon_url(@pokemon), notice: "Pokemon was successfully created." }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1 or /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to pokemon_url(@pokemon), notice: "Pokemon was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1 or /pokemons/1.json
  def destroy
    @pokemon.destroy

    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: "Pokemon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :type1, :type2, :total, :hp, :attack, :defense, :sp_attack, :sp_defense, :speed, :generation, :legendary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/home/_header.html.erb
<nav class="navbar bg-danger">
  <div class="container-fluid">
  	<%= link_to 'Home page', root_path, class:"navbar-brand" %>
  	<%= link_to 'About Us', home_about_path, class:"navbar-brand" %>
    <%= link_to 'Full Pokedex', pokemons_path, class:"navbar-brand" %>
    <%= link_to 'Add New Pokemon', new_pokemon_path, class:"navbar-brand" %>
    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/index.html.erb
<h1>Welcome to the Pokedex!</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pokedex</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon) do |form| %>
  <% if pokemon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
        <% pokemon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :type1, class:"form-control", placeholder:"Type 1" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.text_field :type2, class:"form-control", placeholder:"Type 2" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :total, class:"form-control", placeholder:"Total" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :hp, class:"form-control", placeholder:"HP" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :attack, class:"form-control", placeholder:"Attack" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :defense, class:"form-control", placeholder:"Defense" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :sp_attack, class:"form-control", placeholder:"Special Attack" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :sp_defense, class:"form-control", placeholder:"Special Defense" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :speed, class:"form-control", placeholder:"Speed" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.number_field :generation, class:"form-control", placeholder:"Generation" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.label :legendary, style: "display: block" %>
    <%= form.check_box :legendary, class:"form-check-laber"%>
  </div>
  <br/>

  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/pokemons/_pokemon.html.erb
<div id="<%= dom_id pokemon %>">
  <h1><%= pokemon.name %></h1>
  <table id="pokemons" class="table table-hover">
    <thead class="thead-dark">
        <th scope="col">Type 1</th>
        <th scope="col">Type 2</th>
        <th scope="col">Total</th>
        <th scope="col">HP</th>
        <th scope="col">Attack</th>
        <th scope="col">Defense</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <th scope="col"><%= pokemon.type1 %></th>
          <th scope="col"><%= pokemon.type2 %></th>
          <th scope="col"><%= pokemon.total %></th>
          <th scope="col"><%= pokemon.hp %></th>
          <th scope="col"><%= pokemon.attack %></th>
          <th scope="col"><%= pokemon.defense %></th>
        </tr>
    </tbody>
  </table>
  <br/>
  <table id="pokemons" class="table table-hover">
    <thead class="thead-dark">
        <tr>
        <th scope="col">Special Attack</th>
        <th scope="col">Special Defense</th>
        <th scope="col">Speed</th>
        <th scope="col">Generation</th>
        <th scope="col">Legendary</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <th scope="col"><%= pokemon.sp_attack %></th>
          <th scope="col"><%= pokemon.sp_defense %></th>
          <th scope="col"><%= pokemon.speed %></th>
          <th scope="col"><%= pokemon.generation %></th>
          <th scope="col"><%= pokemon.legendary %></th>
        </tr>
    </tbody>
  </table>
</div>

app/views/pokemons/edit.html.erb
<h1>Editing pokemon</h1>

<%= render "form", pokemon: @pokemon %>

<br>

<div>
  <%= link_to "Show this pokemon", @pokemon, class:"btn btn-warning" %>
  <%= link_to "Back to pokemons", pokemons_path, class:"btn btn-primary" %>
</div>

app/views/pokemons/index.html.erb
<table id="pokemons" class="table table-hover">
  <thead class="thead-dark">
      <tr>
      <th scope="col">Name</th>
      <th scope="col">Type 1</th>
      <th scope="col">Type 2</th>
      <th scope="col">Total</th>
      <th scope="col">HP</th>
      <th scope="col">More information</th>
    </tr>
  </thead>
  <tbody>
      <% @pokemons.each do |pokemon| %>
      <tr>
        <th scope="col"><%= pokemon.name %></th>
        <th scope="col"><%= pokemon.type1 %></th>
        <th scope="col"><%= pokemon.type2 %></th>
        <th scope="col"><%= pokemon.total %></th>
        <th scope="col"><%= pokemon.hp %></th>
        <th>
          <%= link_to "Show this pokemon", pokemon, class:"btn btn-primary" %>
        </th>
      </tr>
      <% end %>
  </tbody>
</table>

<%= link_to "New pokemon", new_pokemon_path, class:"btn btn-warning" %>

app/views/pokemons/new.html.erb
<h1>Create New pokemon</h1>

<%= render "form", pokemon: @pokemon %>

<br>

<div>
  <%= link_to "Back to pokemons", pokemons_path, class:"btn btn-primary" %>
</div>

app/views/pokemons/show.html.erb
<%= render @pokemon %>
</br>
<div>
  <%= link_to "Edit this pokemon", edit_pokemon_path(@pokemon), class:"btn btn-warning" %>
  <%= link_to "Back to pokemons", pokemons_path, class:"btn btn-primary" %>

  <%= button_to "Destroy this pokemon", @pokemon, method: :delete, :class => "btn btn-danger" %>
</div>